# Generated by Django 4.1.7 on 2023-03-31 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('country_code', models.IntegerField(null=True, unique=True)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('capital_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('capital_code', models.IntegerField(null=True, unique=True)),
                ('country_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
